##
# Plugins
require:
  - standard
  - rubocop-rspec

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

##
# Enabled cops
Style/FrozenStringLiteralComment:
  Enabled: true

##
# Disabled cops
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false

##
# Disabled cops (rspec)
RSpec/FilePath:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
RSpec/EmptyLineAfterSubject:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/EmptyLineAfterFinalLet:
  Enabled: false
Style/NilComparison:
  Exclude:
    - spec/ryo_object_spec.rb
RSpec/DescribeClass:
  Enabled: false

AllCops:
  NewCops: disable
  Include:
    - 'lib/*.rb'
    - 'lib/**/*.rb'
    - 'spec/*.rb'
    - 'spec/**/*.rb'
  TargetRubyVersion: 3.3
